# UpdateVersion.ps1
# Usage: pwsh -File UpdateVersion.ps1
# Run this BEFORE you commit to set the count for the upcoming commit.

Write-Host "Fetching latest changes..." -ForegroundColor Yellow
git fetch origin main
git pull --rebase origin main

$CurrentCount = (git rev-list --count HEAD).Trim()
$NextCount = [int]$CurrentCount + 1
$Major = "1"
$Minor = "0"
$Placeholder = "?hash?"
$FullVersion = "$Major.$Minor.$NextCount.$Placeholder"
$ResourceVersion = "$Major.$Minor.$NextCount.0"

Write-Host "Setting version for NEXT commit to: $FullVersion" -ForegroundColor Cyan

# 1. Update src/xkcdversion.pas
$VersionPasPath = "src/xkcdversion.pas"
$VersionPasContent = @"
// Generated by build script - do not edit manually
unit xkcdversion;

interface

const
  CAppVersion = '$FullVersion';

implementation

end.
"@

# Idempotency check for .pas
if (Test-Path $VersionPasPath) {
    $CurrentPas = Get-Content $VersionPasPath -Raw
    if ($CurrentPas -eq $VersionPasContent) {
        Write-Host "xkcdversion.pas is already up to date."
    } else {
        $VersionPasContent | Out-File -FilePath $VersionPasPath -Encoding utf8 -NoNewline
    }
} else {
    $VersionPasContent | Out-File -FilePath $VersionPasPath -Encoding utf8 -NoNewline
}

# 2. Update all .dproj files in src/
$DprojFiles = Get-ChildItem -Path "src/*.dproj"
foreach ($DprojFile in $DprojFiles) {
    $DprojContent = Get-Content -Path $DprojFile.FullName -Raw
    
    $NewContent = $DprojContent -replace "FileVersion=\d+\.\d+\.\d+\.\d+", "FileVersion=$ResourceVersion"
    # Match hash-based format (with placeholder or existing hash) or old X.X.X.X format
    $NewContent = $NewContent -replace "ProductVersion=\d+\.\d+\.\d+\.[^;]+", "ProductVersion=$FullVersion"
    
    if ($NewContent -eq $DprojContent) {
        Write-Host "$($DprojFile.Name) is already up to date."
    } else {
        Write-Host "Updating $($DprojFile.Name)..."
        $NewContent | Out-File -FilePath $DprojFile.FullName -Encoding utf8 -NoNewline
    }
}

Write-Host "Version update complete. You can now commit your changes." -ForegroundColor Green
