# UpdateVersion.ps1
# Usage: pwsh -File UpdateVersion.ps1

$CommitCount = (git rev-list --count HEAD).Trim()
$ShortHash = (git rev-parse --short HEAD).Trim()
$Major = "1"
$Minor = "0"
$FullVersion = "$Major.$Minor.$CommitCount.$ShortHash"
$ResourceVersion = "$Major.$Minor.$CommitCount.0"

Write-Host "Updating version to $FullVersion"

# 1. Update src/xkcdversion.pas
$VersionPasPath = "src/xkcdversion.pas"
$VersionPasContent = @"
// Generated by git hook - do not edit manually
unit xkcdversion;

interface

const
  CAppVersion = '$FullVersion';

implementation

end.
"@
$VersionPasContent | Out-File -FilePath $VersionPasPath -Encoding utf8 -NoNewline

# 2. Update all .dproj files in src/
$DprojFiles = Get-ChildItem -Path "src/*.dproj"
foreach ($DprojFile in $DprojFiles) {
    Write-Host "Updating $($DprojFile.Name)..."
    $DprojContent = Get-Content -Path $DprojFile.FullName -Raw
    
    # Update FileVersion and ProductVersion in VerInfo_Keys and elsewhere
    $DprojContent = $DprojContent -replace "FileVersion=\d+\.\d+\.\d+\.\d+", "FileVersion=$ResourceVersion"
    $DprojContent = $DprojContent -replace "ProductVersion=\d+\.\d+\.\d+\.\d+", "ProductVersion=$FullVersion"
    
    $DprojContent | Out-File -FilePath $DprojFile.FullName -Encoding utf8 -NoNewline
}

Write-Host "Version updated successfully."
