# UpdateVersion.ps1
# Usage: pwsh -File UpdateVersion.ps1 [reference]
param(
    [string]$Reference = "HEAD"
)

$CommitCount = (git rev-list --count $Reference).Trim()
$ShortHash = (git rev-parse --short $Reference).Trim()
$Major = "1"
$Minor = "0"
$FullVersion = "$Major.$Minor.$CommitCount.$ShortHash"
$ResourceVersion = "$Major.$Minor.$CommitCount.0"

Write-Host "Determined version: $FullVersion (from $Reference)"

# 1. Update src/xkcdversion.pas
$VersionPasPath = "src/xkcdversion.pas"
$VersionPasContent = @"
// Generated by build script - do not edit manually
unit xkcdversion;

interface

const
  CAppVersion = '$FullVersion';

implementation

end.
"@

# Idempotency check for .pas
if (Test-Path $VersionPasPath) {
    $CurrentPas = Get-Content $VersionPasPath -Raw
    if ($CurrentPas -eq $VersionPasContent) {
        Write-Host "xkcdversion.pas is already up to date."
    } else {
        $VersionPasContent | Out-File -FilePath $VersionPasPath -Encoding utf8 -NoNewline
    }
} else {
    $VersionPasContent | Out-File -FilePath $VersionPasPath -Encoding utf8 -NoNewline
}

# 2. Update all .dproj files in src/
$DprojFiles = Get-ChildItem -Path "src/*.dproj"
foreach ($DprojFile in $DprojFiles) {
    $DprojContent = Get-Content -Path $DprojFile.FullName -Raw
    
    $NewContent = $DprojContent -replace "FileVersion=\d+\.\d+\.\d+\.\d+", "FileVersion=$ResourceVersion"
    # Match both old X.X.X.X format and new hash-based format in ProductVersion
    $NewContent = $NewContent -replace "ProductVersion=\d+\.\d+\.\d+\.[0-9a-f]+", "ProductVersion=$FullVersion"
    $NewContent = $NewContent -replace "ProductVersion=\d+\.\d+\.\d+\.\d+", "ProductVersion=$FullVersion"
    
    if ($NewContent -eq $DprojContent) {
        Write-Host "$($DprojFile.Name) is already up to date."
    } else {
        Write-Host "Updating $($DprojFile.Name)..."
        $NewContent | Out-File -FilePath $DprojFile.FullName -Encoding utf8 -NoNewline
    }
}

Write-Host "Version update complete."
